### ISSUE TITLE
Google TTS don, 't send text to my google home mini

### ISSUE THREAD

**Issue by asmit8850** [denniedegroot/com.google.tts#10]
Version v1. 3.1. If I send a broadcast text to all devices, then my google home is speaking the wanted text. If I only send a text to my google home mini, then nothing happens. Do I Something wrong?

**Comment by denniedegroot** [comment]
This should work. Maybe try to restart your google home/homey and try again?

**Comment by asmit8850** [comment]
Thanks, it is works
