### ISSUE TITLE
Norwegian

### ISSUE THREAD

**Issue by jahnkenneth** [denniedegroot/com.google.tts#12]
Could you please add Norwegian? :-) 
It is supported by Google assistant

**Comment by denniedegroot** [comment]
Oh how could I forget Norway, I will add it in the next release :)

**Comment by jahnkenneth** [comment]
Easy mistake, not that many people living here ;-)
Looking forward to the next update! :-D

**Comment by denniedegroot** [comment]
Support has been added in 1.3.2 which is under review by Athom. Should be in the app store in a couple of days. If you have any issues then you can re-open this issue.

**Comment by jahnkenneth** [comment]
The Norwegian Google assistant has gotten a new male voice. Would it be possible to choose this one? The default Norwegian TTS voice is crappy...
