### ISSUE TITLE
Support to TTS from Homey to a Sonos One running Google Assistant?

### ISSUE THREAD

**Issue by michelhelsdingen** [denniedegroot/com.google.tts#13]
If at all possible off course. Just throwing this out there.

**Comment by denniedegroot** [comment]
Unfortunately this is not possible when the device has no chromecast support.

**Comment by michelhelsdingen** [comment]
All good, created a feauture request at Athom, thanks again!

**Comment by Paxens87** [comment]
@denniedegroot So this will not be available for SONOS. Would be great if i could use my SONOS as device to tell my family it´s dinner time or similar things

**Comment by denniedegroot** [comment]
@Paxens87 no this is only possible of SONOS supports the chromecast feature.
