### ISSUE TITLE
Unable to select individual GH any more

### ISSUE THREAD

**Issue by rhannink** [denniedegroot/com.google.tts#14]
Hello,

TTS worked fine untill a few Days ago. The GH mini in the livingroom keeps silent.
When I make a new flow with TTS action card, I can only select **Broadcast to all devices**, but no individual GH's anymore?

Gr. Remco

**Comment by denniedegroot** [comment]
Have you restarted your Homey and tried again?

**Comment by rhannink** [comment]
Yep, after reboot, still the Same Problem. TTS is not working and I cannot select the individual GH devices for playback, just the **Broadcast to all devices** Option.

**Comment by rhannink** [comment]
Also restarted the GH’s. No difference and dit a Pull The Plug (PTP) restart of Homey. Everyrhing without result. TTS keeps silence an I cannot select individual GH’s to let them say something.

**Comment by denniedegroot** [comment]
Well if no devices are showing then the 'mdns' service is blocked by something. Broadcast to all devices will always show even when you have no devices. Did you maybe changed the router or installed a new switch?

**Comment by rhannink** [comment]
Thanks Dennie,

That was the problem. For Some reason mDNS was disabled on my Unifi accespoints and controller. I have no idea how this happend, but after enabling it and restarting the accespoints all works fine again.
