### ISSUE TITLE
Differentiate between UK English and US English (and male/female)

### ISSUE THREAD

**Issue by woutf** [denniedegroot/com.google.tts#17]
Right now when selecting English, users are presented with a British sounding voice. I'm not familiar with how many different voices the tts-engine supports, but would it be possible to split the English option between UK and US? And would the tts-engine also support choosing either a male or female voice?

**Comment by denniedegroot** [comment]
I added the English US/AU versions in 1.4.0.
There is no selection available for male/female, there is only 1 voice per country.
