### ISSUE TITLE
promise was rejected with a falsy true - Not running Google TTS voice

### ISSUE THREAD

**Issue by rodroz** [denniedegroot/com.google.tts#21]
Hi,

This morning google tts stopped working. 
When trying to create a new card the Google home is not visible in devices, just broadcast.
Using broadcast times out and no speech is getting through. Is there any change that might have triggered this ?

Homey reports promise was rejected with a falsy true when pressing the red triangle on the failed card after running.

Resetted Home and Homey.

**Comment by denniedegroot** [comment]
Hi, something must have changed in your network because it is still working for most users.
Can you send me a log file? You can do this in the Homey App and the go to the Google TTS app and send a report.

**Comment by rodroz** [comment]
Hi Dennis,

Log file with reference : 5f2f45d7-8c20-4168-9384-731ed0f46353

**Comment by rodroz** [comment]
Got it to work for about one hour yesterday after factory resetting Google home.. Today the home is not showing in devices again, only broadcast when choosing which device to play speech through.
