### ISSUE TITLE
Setting Volume with variable does not work

### ISSUE THREAD

**Issue by SynoUser-NL** [denniedegroot/com.google.tts#23]
Hi,

I've declared a Number variable in Logic with a value. In my Flow Google TTS card I opted to set the volume to that variable. The Flow saves just fine, just when I test it I get a token_out_of_range error.
I tried different values, but that appears to make no difference. Setting the Volume as a % with the slider instead of a variable solves the problem.

I don't think I'm doing anything wrong, but let me know if I am. If not, can you please fix this so I can set a General volume by variable?

Thank you!
Den

**Comment by ehdegroot** [comment]
I just wanted to report this... same issue here, same error message.

**Comment by sossienl** [comment]
Ah this is the reason. See issue #25

**Comment by denniedegroot** [comment]
5369abc9b72614833fc5350f145ed4a2391c02d6 Should fix this
