### ISSUE TITLE
Sonos speakers with Google Assistant

### ISSUE THREAD

**Issue by TheArcturian** [denniedegroot/com.google.tts#24]
Is your Google TTS app supposed to see Sonos speakers with the Google Assistant service installed?

In the flow, I only see the option "Broadcast" and not any spesific speakers. I guess it should have listed my two Google Assistant-enabled Sonos speakers, but maybe I need to configure something more?

**Comment by denniedegroot** [comment]
Unfortunately this is not possible when the device has no chromecast support.
