### ISSUE TITLE
V1.4.2 error

### ISSUE THREAD

**Issue by JPe2** [denniedegroot/com.google.tts#27]
What’s new in v1.4.2
Fix setting volume with a tag

Great solution. Unfortunately, all the volume settings in the flows are set to Zero by updating to this version!

![Clipboarder 2020 10 05](https://user-images.githubusercontent.com/3833862/95068859-2496e880-0706-11eb-83a5-aa487037bdfb.png)

The value of the Variable is 0,4

When running: Error: Token Invalid step, so does not work////////
EDIT:   when the variable value is set to 40, it is working fine 👍

**Comment by denniedegroot** [comment]
Variables only work with round numbers from 1 - 100.
Volume settings are indeed changed, nothing I can do about that unfortunately.
