### ISSUE TITLE
Google TTS not working.

### ISSUE THREAD

**Issue by pjmpessers** [denniedegroot/com.google.tts#31]
Hello Dennie.

From what i understand was there a change in the google api. This way the Google TTS app on homey is broken.

Therefor a few questions:
- Are you aware that it\s broken?
- Are you working on a fix?
- When will this be ready?

I know i ask a lot. I would like to donate a small fee. But i don't want to use paypall. Maybe it can be done by bank transfer.

**Comment by shaarkys** [comment]
https://github.com/denniedegroot/com.google.tts/issues/30

**Comment by denniedegroot** [comment]
See #30
