### ISSUE TITLE
TTS to speaker pair doesn’t work

### ISSUE THREAD

**Issue by ghost** [denniedegroot/com.google.tts#34]
TTS to speaker pair doesn’t work.
i have paired two mini’s to one stereo pair but then TTS doesn’t work. Homey is not giving an error and playing music through google home does work.

bug or api issue?

**Comment by otteminat0r** [comment]
Hi
I have the dame issue.  Seems to not work with speaker pair.
Seems like this has been a issue for a long time.
Any idea on when this will be fixed?

Tnx

**Comment by dudz40** [comment]
speaker pair should work in the next release.
