### ISSUE TITLE
No speech

### ISSUE THREAD

**Issue by dracoignis** [denniedegroot/com.google.tts#35]
Until 2 days ago i had messages spoken on my Google nest speakers. The last 2days i hear a “ping”, and the moment it should start speaking theres no message. Restarted homey, the speaker, resynced google home,... nothing fixed the problem

**Comment by shaarkys** [comment]
do you have correctly set volume ?
Anyway, working on my side....

**Comment by dracoignis** [comment]
Yes, all my messages get their volume from a variabele thas set on 50 permanently

**Comment by BrapBrapp2** [comment]
Have exactly the same problem, started 3-4 days ago.

**Comment by dracoignis** [comment]
I just retested a flow who has a Google tts actioncard, and got this message.
![Uploading 1B9849B1-D2CE-4E4C-94E3-70966ECDCD5B.jpeg…]()

**Comment by dracoignis** [comment]
![CED0716E-F84A-4ABE-A0C8-74E59746C3F4](https://user-images.githubusercontent.com/11711031/118704889-e1faca00-b817-11eb-8fcb-d852383d2d42.jpeg)

**Comment by FingolSE** [comment]
Same here, restarted Google TTS app but still no talking at all, blipp, ping and then silence. Started 3-4 days ago

**Comment by EndorianBlizzard** [comment]
Same here, stopped working 3 to 4 days ago. Volume control is working but there is no talking. Rebooted Homey, removed the app, removed the link between Homey and Google and did the whole shabang the other way around to see if it would work, it ended up in the blipp ping silence.

**Comment by spoelly** [comment]
I can confirm the issue also

**Comment by flits** [comment]
![Screenshot_20210523-001111_Homey](https://user-images.githubusercontent.com/3659189/119242933-8bb4c080-bb62-11eb-9861-c3120009831a.jpg)

Have the same issue. But without any change started working again after 4 days. But the same way it was fixed (no change), it stopped working again.

**Comment by Peterstark86** [comment]
Some speakers works sometimes, others do not speak at all. No firmware updates or something like that, the problem started from nowhere for me.

**Comment by flits** [comment]
Same here. Google speakers randomly work and stops working again.

**Comment by shaarkys** [comment]
So I realized it doesn't work for me either.

**Comment by denniedegroot** [comment]
It does work for me, so I am not sure what is going on.

**Comment by JensGuBe** [comment]
I have the same problem. A couple of weeks ago all speaking stopped. Only the "ploijk-sound" in the beginning and then silent.

**Comment by dracoignis** [comment]
> It does work for me, so I am not sure what is going on.

Could homeyversion be zn issue? Im at 6.1.0

**Comment by JensGuBe** [comment]
I'm also at 6.1.0 in a Homey (Early 2019)
It worked fine for a couple of weeks after upgrade to 6.1.0. I don't know about any other upgrades when TTS stopped speaking.
________________________________

**Comment by Willieku** [comment]
@denniedegroot  i conform. It does not work for several weeks now.
Perhaps it the problem is that my homey are to old? Or the google mini to old?

**Comment by flits** [comment]
@denniedegroot is it still working on your homey?

**Comment by HansieNL** [comment]
Same issue here. Ping sound and then silence.
Diagnostic rapport: 532978f3-a3cd-4972-bdeb-c95421482dee
I hope the rapport can help to solve the problem.

**Comment by JPe2** [comment]
Also for me it is not workong anymore, I have 1 google-home-mini and 1 google-nest-mini, both no speach anymore (casting still can be done )

**Comment by PeterKawa** [comment]
Hi Dennie, a few days ago it stopped working here too. Only the "start pling" is played. Homey v7.0.0-rc8 (installed at May 27th 2021)
Google TTS v1.4.2
Also the app crashed today (which never did before), but I forgot to generate a crashreport b4 restarting the app :(
When testing a flow, a "V" and not a "X" or "!" is displayed on the TTS flowcard
![TTS](https://user-images.githubusercontent.com/74005072/121015438-4962c480-c79b-11eb-8705-14d04ae28530.png)
Thanks for the great app, and I hope you have a fix for it.

**Comment by flits** [comment]
She suddenly talks again. She does have a different voice. But without changing anything on my side, it works again ☺️

**Comment by JensGuBe** [comment]
Same for me. I have not tested all flows but some suddenly worked yesterday evening. 😃

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Willieku** [comment]
Me to
Great dennie
Ik think the voice is somthing like a dutch tts
Ik you make it, thanks to Dennie

Op di 8 jun. 2021 06:20 schreef JensGuBe ***@***.***>:

**Comment by BrapBrapp2** [comment]
Works again! 😄👍😄

**Comment by dracoignis** [comment]
Works again for me too, different voice, but the message is clear. So ill close the issue
