### ISSUE TITLE
Homey pro 2023 

### ISSUE THREAD

**Issue by nissenhj** [denniedegroot/com.google.tts#37]
Will you update this app to work with the new Homey pro 2023?

**Comment by shaarkys** [comment]
@denniedegroot  - do you think you would agree on transferring it to new developer, in case you will have no time to maintain it anymore, who can port it to SDK3 ? 

https://community.homey.app/t/google-text-to-speech-tts/29770/130?u=sharkys

Thank you.

**Comment by denniedegroot** [comment]
This app will be ported to SDKv3 in due time.

**Comment by dudz40** [comment]
Hi Dennie, I have modified your work to be compliant with SDK3 and modified /added some other things as well (stereo pair, not sending to muted device as an option). 
Needed to change the Google-Home-Audio-TTS module into a class and moved it to lib.
Can be found in https://github.com/dudz40/com.verbem.googleTTS.
This can be found in the community store (HCS).
If you are okay, I will try and publish it as well into the official store, otherwise feel free to copy/modify and publish.

**Comment by denniedegroot** [comment]
Hi @dudz40 , great work! Can you maybe create a pull request, then I can merge and release it.

**Comment by shaarkys** [comment]
Hi @denniedegroot , I saw you are not so active anymore on the Homey side nor on the Community forum and not sure how much you have progressed yourself on the SDK rewrite....even I have been using GoogleTTS for long time thanks to you, don't you want to please transfer it to Martin? Just asking...because I understood this it has been full rewrite...

**Comment by denniedegroot** [comment]
@shaarkys I have made progression but not finished. Also I am active on the Homey side just not on the forums. The new Homey only needs SDKv3 compatibility and is only shipped to developers that's why I haven't finished it myself.

**Comment by dudz40** [comment]
I have a new Pro, this app is tested on the new platform .

Martin Verbeek

Op di 7 feb. 2023 18:06 schreef Shaarkys ***@***.***>:

**Comment by dudz40** [comment]
> Hi @dudz40 , great work! Can you maybe create a pull request, then I can merge and release it.

pull request was created, if you can check it out and see if it passes release, much obliged, Martin

**Comment by denniedegroot** [comment]
https://homey.app/a/com.google.tts/test/

Thanks to @dudz40 !
I still need to merge some code but please test if you can and let me know if it works.

**Comment by twanniee** [comment]
Hi Dennie
I cannot sent text to some devices, like google nest hub and beoplay. 
They just don't show up as an option. 
In the old version it works perfect.

**Comment by denniedegroot** [comment]
Yeah the discovery of devices isn't really stable. If you restart the app sometimes it will find more devices. This is something I am working on.

**Comment by twanniee** [comment]
Thanks Dennie.
Good to know.
Thanks for your work

Van: denniedegroot ***@***.***>
Datum: zaterdag, 25 februari 2023 om 14:17
Aan: denniedegroot/com.google.tts ***@***.***>
CC: Twan Wouters ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [denniedegroot/com.google.tts] Homey pro 2023 (Issue #37)

Yeah the discovery of devices isn't really stable. If you restart the app sometimes it will find more devices. This is something I am working on.

**Comment by denniedegroot** [comment]
@twanniee it should be solved in 2.0.1. Can you check?

**Comment by twanniee** [comment]
Dennie,
Het werkt nu perfect!

Van: denniedegroot ***@***.***>
Beantwoorden - Aan: "denniedegroot/com.google.tts" ***@***.***>
Datum: dinsdag 28 februari 2023 om 19:16
Aan: "denniedegroot/com.google.tts" ***@***.***>
CC: Twan Wouters ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [denniedegroot/com.google.tts] Homey pro 2023 (Issue #37)


@twanniee<https://github.com/twanniee> it should be solved in 2.0.1. Can you check?

**Comment by JPe2** [comment]
Cast a text to Google V2.01 Veel 'oude' flows werken niet meer omdat de lay-out van de 'dan' kaart is gewijzigd:
![image](https://user-images.githubusercontent.com/3833862/223383250-0eb1338e-6c16-41c5-adab-2d8f2ca1c9b1.png)

Er moet nu gekozen worden voor 'Ja' of 'Nee' na de tekst 'langzaam, of door een boolean tag, dan werkt dit weer.

Na de tekst 'ook naar gedempt' moet een zelfde keuze gemaakt worden, maar bij deze keuze werkt 'Ja' of 'Nee' niet, alleen als er een boolean tag wordt ingevuld, dan werkt het. Met de web-app komt dit probleem voor, met de mobiel-app werkt het wel goed.

Een waarschuwing dat er veranderingen in de FlowKaarten zou zijn, had ik op prijs gesteld.
Verder maak ik al jaren naar tevredenheid gebruik van deze app, hartelijk dank daarvoor en dank voor de aanpassing.

**Comment by PeterKawa** [comment]
I confirm the issue JPe2 reported.
Isn't it possible in a future update, for existing flowcards, to adjust them again, but now enter No and No to both fields by default?

**Comment by shaarkys** [comment]
I had to perform fix for all my flows, used Device capabilities (Get Flows Containing) to find those flows.
A pity it's not discovered by any of the check, everything seems to be fine until you try to save a flow.
