### ISSUE TITLE
Gehele app werkt niet meer

### ISSUE THREAD

**Issue by sossienl** [denniedegroot/com.google.tts#39]
Helaas lijkt sinds een aantal dagen de app niet meer te werken.

Ik krijg de volgende foutmelding bij al mijn cards:

Encountered an unexpected error value: "undefined"

Ook het discoveren van mijn cast devices werkt niet meer, ik zie alleen Broadcast to all.

Report:

80e8ff6c-6546-467e-a90a-99b6e7bc7951

**Comment by denniedegroot** [comment]
Are you using a Homey Pro 2023? If so then that is currently the problem. A future firmware update from Athom should fix it.

**Comment by sossienl** [comment]
Ja! Ok helder. Fingers crossed.

**Comment by sossienl** [comment]
Rc98 fixed it
