### ISSUE TITLE
Google home mini crashes

### ISSUE THREAD

**Issue by qwerty123abc** [denniedegroot/com.google.tts#6]
Every time I use Google TTS my Google Home Mini crashes and starts to reboot and the Homey app says it has stopped suddenly. Is there someway to solve this?
I tried to reinstall the app and restart Homey and the Mini but it keeps crashing. I use 1.3 version of the app and the latest Homey stable firmware.

**Comment by denniedegroot** [comment]
This is difficult to solve I think. Can you try this again and report the time that the crash occurred?

**Comment by qwerty123abc** [comment]
Hi,

It worked for a few times. But now the google home mini and the app  keep crashing again. The time was 10:39 in the morning. I made a diagnostic rapport. 

b6b15e4a-879e-49eb-ad19-7373c209e083

I hope you can see anything..

**Comment by denniedegroot** [comment]
The log doesn't contain anything, it looks like the app hasn't even started yet.
I just pushed a fix for an issue, maybe you could try this and see if it fixes your problem too?

**Comment by qwerty123abc** [comment]
Hi, the problem of all this is not in the app or Homey. The problem was in the power supply. With a new cable for my Google Home Mini the problem is solved. This issue can be closed. Thanks!
