### ISSUE TITLE
Doesn't read out 'minus'

### ISSUE THREAD

**Issue by grenness** [denniedegroot/com.google.tts#7]
I believe that I can't hear it say 'minus' in front of negative values. But I might be wrong.
I use it to read out loud the outside temperature measured by my Netatmo, but when it's -2.5° it only says 'two-point-five' and not 'MINUS two-point-five'.
Anyone else experiencing this?

**Comment by denniedegroot** [comment]
This is out of my control, the text is translated by google and converted to audio.
