### ISSUE TITLE
text box too low with Homey flow web

### ISSUE THREAD

**Issue by Reemster** [denniedegroot/com.google.tts#8]
I try the app. But i have problems with enter some text and use the tag. I can't lower the screen. Is this what a user can fix? (don't know how) or what Athom must fix? or the app maker?

See pictures. 
![zucht](https://user-images.githubusercontent.com/19860405/54077980-de2a9f00-42c0-11e9-9b01-6500e40caab6.jpg)
![dubbel zucht](https://user-images.githubusercontent.com/19860405/54077981-dff46280-42c0-11e9-8fb1-0774077b6bc8.jpg)

**Comment by denniedegroot** [comment]
That is something for Athom to fix. An app developer has no influence on the design.
